--- #YAML:1.0
name:                       Labyrinth::Demo
version:                    1.00
abstract:                   Labyrinth Website Management Framework - Demo Website
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  Labyrinth:	              5.03
  Labyrinth::Plugin::Core:	5.04
recommends:
  Test::More:               0.70
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
  Test::CPAN::Meta:         0.13
  Test::JSON::Meta:         0.08
build_requires:
  Test::More:               0.01

provides:
  Labyrinth::Demo:
    file:     lib/Labyrinth/Demo.pm
    version:  1.00

no_index:
  directory:
    - t
    - vhost

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Demo

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
