--- #YAML:1.0
name:                       Labyrinth::Demo
version:                    1.01
abstract:                   Labyrinth Website Management Framework - Demo Website
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  perl:                     5.006
  Labyrinth:	              5.14
  Labyrinth::Plugin::Core:	5.04
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Test::More:               0.01

provides:
  Labyrinth::Demo:
    file:     lib/Labyrinth/Demo.pm
    version:  1.01

no_index:
  directory:
    - t
    - vhost

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Demo
  repository: http://github.com/barbie/labyrinth-demo

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
